### ISSUE TITLE
failed to build to webassembly

### ISSUE THREAD

**Issue by TorosFanny** [xu-cheng/katex-rs#2]
When compiling code simply like this
```rust
fn main() {
  let formula1 = katex::render("E = mc^2").unwrap();

  let opts = katex::Opts::builder().display_mode(true).build().unwrap();
  let formula2 = katex::render_with_opts("E = mc^2", opts).unwrap();
}
```
with command
```
cargo web build
```

Then it reports:
```
note: rust-lld: error: unknown file type: quickjs.nolto.o
```

**Comment by xu-cheng** [comment]
This library is primarily to be used for server side rendering. It utilizes [quickjs](https://github.com/theduke/quickjs-rs), which is a JS interpreter written in C. Currently, it does not support webassembly target.

It is possible to build in webassembly with [this patch](https://github.com/theduke/quickjs-rs/pull/57) and emscripten.

However, if your use case is running KaTeX inside browser. A better solution would be to call KaTeX JS directly through wasm-bindgen.
